version: '3.3'
services:
    mysql:
        container_name: mysql-app
        restart: always
        build:
            context: ./mysql
            dockerfile: Dockerfile
        ports:
            - "3336:3306"
        volumes:
            - ./mysql/.dbdata:/var/lib/mysql
            - ./mysql/scripts:/home
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: app
            MYSQL_USER: root
            MYSQL_PASSWORD: 123